### ISSUE TITLE
TypeError when using w_retrain mode on resnet18 cifar10

### ISSUE THREAD

**Issue by puigde** [OPTML-Group/Unlearn-WorstCase#2]
Hi there! I am trying to use the worst case unlearn set generator with the retrain mode but getting the following error trace:
```
Traceback (most recent call last):
  File "/home/ppol/Unlearn-WorstCase/data-wise/main_selmu.py", line 216, in <module>
    main()
  File "/home/ppol/Unlearn-WorstCase/data-wise/main_selmu.py", line 121, in main
    unlearn_method(train_full_loader, model, criterion, args, w, mask)
  File "/home/ppol/Unlearn-WorstCase/data-wise/unlearn/impl.py", line 313, in _wrapped
    train_acc = unlearn_iter_func(
TypeError: w_retrain() takes 7 positional arguments but 8 were given
```

Command to reproduce the error:
```bash
python main_selmu.py --arch resnet18 --dataset cifar10 --cp_path results/cifar10/0model_SA_best.pth.tar --num_indexes_to_replace 4500 --unlearn w_retrain --unlearn_steps 182 --save_dir results/cifar10
```

Am I specifying the launching command wrong? I tried to follow [the data-wise link](https://github.com/OPTML-Group/Unlearn-WorstCase/tree/main/data-wise)

In the future I would like to use other unlearning methods besides w_retrain. An example command for each one as in the paper or a config file would have been very helpful.

For reference the resnet checkpoint was obtained with the following command:
```bash
python main_train.py --dataset cifar10 --save_dir "results/cifar10"
```

**Comment by a-F1** [comment]
Thank you for your appreciation and recognition of our work. In our approach, we use Fine Tuning (FT) with SignSGD to solve the lower level. Of course, you can use other methods as well. We have updated the code to support solving the lower level with Retrain.

If you would like to use another method, such as Random Label (RL), for solving, you can modify `--unlearned` to `w_RL`. The specific command is as follows:
```python
python main_selmu.py --arch resnet18 --dataset cifar10 --cp_path results/cifar10/0model_SA_best.pth.tar --num_indexes_to_replace 4500 --unlearn w_RL --unlearn_steps 10 --save_dir results/cifar10
```

If you have any other questions, please feel free to contact us!

**Comment by a-F1** [comment]
The issue has been closed. If you have any further questions, please feel free to contact us.
