### ISSUE TITLE
Unspecified pruner dependency

### ISSUE THREAD

**Issue by puigde** [OPTML-Group/Unlearn-WorstCase#3]
Hi there! I came upon a missing dependency in `Unlearn-WorstCase/data-wise/unlearn/impl.py` named `pruner` (l:6, l:9). Does not seem to match the [pruner pip package](https://pypi.org/project/pruner/). Is this maybe related to [torch-pruning](https://pypi.org/project/torch-pruning/)?

For now I commented it out :):)

Thanks in advance !!

**Comment by a-F1** [comment]
Thank you for your interest and support in our work!  `pruner` is not used in our code, and its inclusion was an oversight during our code preparation. You can simply remove it, and we have updated our code.
If you have any other questions, please feel free to contact us.

**Comment by a-F1** [comment]
The issue has been closed. If you have any further questions, please feel free to contact us.
